// Neil's Android Interview-First Plan — extracted from Neil_Android_InterviewFirst_v5.xlsx
const PHASES = [
  {id:1,name:"Reboot + Foundations",weeks:"1–3",color:"var(--p1)"},
  {id:2,name:"Modern Android Stack",weeks:"4–6",color:"var(--p2)"},
  {id:3,name:"Architecture + Testing",weeks:"7–9",color:"var(--p3)"},
  {id:4,name:"AI + Polish",weeks:"10–12",color:"var(--p4)"},
  {id:5,name:"System Design + Sprint",weeks:"13–16",color:"var(--p5)"},
];

// Each week: tasks grouped. type: android | dsa | git | apply
const WEEKS = [
  {w:1,p:1,dates:"Jun 3–9",focus:"Kotlin syntax reboot",apply:false,tasks:[
    {g:"android",t:"Kotlin Koans: data classes, sealed, generics, lambdas"},
    {g:"android",t:"Kotlin Collections docs: map / filter / groupBy / flatMap"},
    {g:"android",t:"Q&A Recordings — background listening"},
    {g:"android",t:"Watch: Philipp Lackner – Kotlin Crash Course"},
    {g:"dsa",t:"NeetCode Easy: Two Sum (20 min)"},
    {g:"dsa",t:"NeetCode Easy: Contains Duplicate"},
    {g:"dsa",t:"NeetCode Easy: Valid Anagram"},
    {g:"git",t:"Project: kotlin-collections-demo — CLI app, 10 collection ops"},
    {g:"git",t:"Start resume draft"},
  ]},
  {w:2,p:1,dates:"Jun 10–16",focus:"Coroutines & Flows · Resume + LinkedIn DONE",apply:false,tasks:[
    {g:"android",t:"Roman Elizarov YouTube: Kotlin Coroutines playlist"},
    {g:"android",t:"kotlinx.coroutines guide end-to-end"},
    {g:"android",t:"Philipp Lackner – Coroutines & Flows playlist"},
    {g:"dsa",t:"NeetCode Easy: Group Anagrams"},
    {g:"dsa",t:"NeetCode Easy: Top K Frequent Elements"},
    {g:"dsa",t:"NeetCode Easy: Product of Array Except Self"},
    {g:"git",t:"Project: coroutines-playground — 10 .kt files, one per concept"},
    {g:"apply",t:"✅ Finish resume + update LinkedIn (QA→Android story)"},
  ]},
  {w:3,p:1,dates:"Jun 17–23",focus:"MVVM + Jetpack basics · Research companies",apply:false,tasks:[
    {g:"android",t:"Architecture Masterclass — first 4 hrs"},
    {g:"android",t:"Android App Architecture guide (developer.android.com)"},
    {g:"android",t:"Philipp Lackner – MVVM Architecture playlist"},
    {g:"dsa",t:"NeetCode: Valid Palindrome"},
    {g:"dsa",t:"NeetCode: Two Sum II"},
    {g:"dsa",t:"NeetCode: Best Time to Buy & Sell Stock"},
    {g:"git",t:"Project: mvvm-todo-no-ui — ViewModel + Repository + UseCase + unit tests"},
    {g:"apply",t:"List 20 target companies"},
  ]},
  {w:4,p:2,dates:"Jun 24–30",focus:"Jetpack Compose deep dive · 🚀 START APPLYING",apply:true,tasks:[
    {g:"android",t:"Workshop Collection — Compose workshops"},
    {g:"android",t:"Compose recomposition + performance talks"},
    {g:"android",t:"PL Coding: Compose Masterclass (120+ lessons)"},
    {g:"dsa",t:"NeetCode Medium: Longest Substring Without Repeat (25 min)"},
    {g:"dsa",t:"NeetCode Medium: Permutation in String"},
    {g:"git",t:"Project: compose-component-library — 8 custom Compose components"},
    {g:"apply",t:"🚀 Send first 3–5 job applications"},
  ]},
  {w:5,p:2,dates:"Jul 1–7",focus:"Retrofit, Room, Hilt, offline-first",apply:true,tasks:[
    {g:"android",t:"Workshop Collection — architecture/DI workshop"},
    {g:"android",t:"Codelabs: WorkManager, DataStore, Room + coroutines"},
    {g:"android",t:"Coding in Flow – Retrofit + Room + Hilt playlist"},
    {g:"dsa",t:"NeetCode Medium: Valid Parentheses (25 min)"},
    {g:"dsa",t:"NeetCode Medium: Min Stack"},
    {g:"dsa",t:"NeetCode Medium: Daily Temperatures"},
    {g:"git",t:"Project: offline-notes-app — Retrofit + Room + Hilt + offline + Compose"},
    {g:"apply",t:"Follow up on Week 4 applications · 3–5 new apps"},
  ]},
  {w:6,p:2,dates:"Jul 8–14",focus:"Portfolio App #1 — interview-ready",apply:true,tasks:[
    {g:"android",t:"App Challenges — brief for Portfolio App #1"},
    {g:"android",t:"Build News Reader or Weather App (Compose, MVVM, Hilt, Retrofit, Room, 4+ screens)"},
    {g:"android",t:"Reference: google/nowinandroid architecture"},
    {g:"dsa",t:"NeetCode Medium: Binary Search (25 min)"},
    {g:"dsa",t:"NeetCode Medium: Search a 2D Matrix"},
    {g:"dsa",t:"NeetCode Medium: Find Min in Rotated Array"},
    {g:"git",t:"Project: portfolio-app-1-news — polished README + screenshots + diagram"},
    {g:"apply",t:"3–5 applications"},
  ]},
  {w:7,p:3,dates:"Jul 15–21",focus:"Multi-module architecture",apply:true,tasks:[
    {g:"android",t:"Architecture Masterclass — 70–80%, process death + state"},
    {g:"android",t:"google/nowinandroid — study module structure"},
    {g:"android",t:"Refactor App #1 into app/data/domain modules"},
    {g:"dsa",t:"NeetCode Medium: Reverse Linked List (25 min)"},
    {g:"dsa",t:"NeetCode Medium: Merge Two Sorted Lists"},
    {g:"dsa",t:"NeetCode Medium: Linked List Cycle"},
    {g:"git",t:"Project: portfolio-app-1-multimodule — before/after README"},
    {g:"apply",t:"3–5 applications"},
  ]},
  {w:8,p:3,dates:"Jul 22–28",focus:"Automated testing 🔑 Your QA superpower",apply:true,tasks:[
    {g:"android",t:"Workshop Collection — testing workshops"},
    {g:"android",t:"Android Testing codelabs: Espresso + Compose UI testing"},
    {g:"android",t:"Hit 70%+ coverage on Portfolio App #1 + coverage badge"},
    {g:"dsa",t:"NeetCode Medium: Remove Nth Node (25 min)"},
    {g:"dsa",t:"NeetCode Medium: Reorder List"},
    {g:"dsa",t:"NeetCode Medium: Find the Duplicate Number"},
    {g:"git",t:"Project: portfolio-app-1-tested — unit + UI tests, CI badge"},
    {g:"apply",t:"5–8 applications"},
  ]},
  {w:9,p:3,dates:"Jul 29–Aug 4",focus:"Android internals + CI/CD",apply:true,tasks:[
    {g:"android",t:"Mini Challenges — 2–3 Compose/architecture challenges"},
    {g:"android",t:"Android Dev Summit: Lifecycle edge cases, ViewModel internals"},
    {g:"android",t:"GitHub Actions pipeline on Portfolio App #1"},
    {g:"dsa",t:"NeetCode Medium: Invert Binary Tree (25 min)"},
    {g:"dsa",t:"NeetCode Medium: Max Depth of Binary Tree"},
    {g:"dsa",t:"NeetCode Medium: Same Tree"},
    {g:"git",t:"Project: cicd-pipeline-demo — build + test on every push/PR"},
    {g:"apply",t:"5–8 applications"},
  ]},
  {w:10,p:4,dates:"Aug 5–11",focus:"Android AI APIs — ML Kit + Gemini",apply:true,tasks:[
    {g:"android",t:"Google ML Kit codelabs: text recognition, smart reply, language ID"},
    {g:"android",t:"Gemini API for Android quickstart (ai.google.dev)"},
    {g:"android",t:"Q&A Recordings: any AI/recent sessions"},
    {g:"dsa",t:"NeetCode Medium: Level Order Traversal (30 min)"},
    {g:"dsa",t:"NeetCode Medium: Validate BST"},
    {g:"dsa",t:"NeetCode Medium: Kth Smallest in BST"},
    {g:"git",t:"Project: mlkit-demo-app — OCR, language detect, smart reply"},
    {g:"apply",t:"5–8 applications"},
  ]},
  {w:11,p:4,dates:"Aug 12–18",focus:"Build Portfolio App #2 (AI-featured)",apply:true,tasks:[
    {g:"android",t:"App Challenges — brief for Portfolio App #2"},
    {g:"android",t:"Build voice journal (ML Kit + Gemini) or smart recipe finder"},
    {g:"android",t:"Must have: Compose, MVVM, Hilt, Room + visible AI feature"},
    {g:"dsa",t:"NeetCode Medium: LRU Cache (30 min)"},
    {g:"dsa",t:"NeetCode Medium: Design Twitter"},
    {g:"dsa",t:"NeetCode Medium: Design HashMap"},
    {g:"git",t:"Project: portfolio-app-2-ai — clear Gemini/ML Kit feature"},
    {g:"apply",t:"5–8 applications"},
  ]},
  {w:12,p:4,dates:"Aug 19–25",focus:"Polish App #2 + CI/CD",apply:true,tasks:[
    {g:"android",t:"Add unit tests + GitHub Actions pipeline + demo GIF"},
    {g:"android",t:"Architecture diagram + 'How AI is used' README section"},
    {g:"android",t:"Mini Challenges — 2–3 more"},
    {g:"dsa",t:"NeetCode Review: redo every slow problem, clean Kotlin (30 min)"},
    {g:"git",t:"Project: portfolio-app-2-polished — tests + CI/CD + README"},
    {g:"apply",t:"5–8 applications"},
  ]},
  {w:13,p:5,dates:"Aug 26–Sep 1",focus:"Mobile system design crash course 📐",apply:true,tasks:[
    {g:"android",t:"ByteByteGo: Design Instagram, Chat App, Ride-Sharing"},
    {g:"android",t:"Alex Xu System Design Vol.1 — news feed, chat, notifications"},
    {g:"android",t:"weeeBox/mobile-system-design framework"},
    {g:"android",t:"Write 3 system design docs in your own words"},
    {g:"dsa",t:"NeetCode Design + weak spots · 1 medium in 25 min timed"},
    {g:"git",t:"Project: system-design-docs — 3 written breakdowns (Markdown)"},
    {g:"apply",t:"Full send — 5–10 applications/week"},
  ]},
  {w:14,p:5,dates:"Sep 2–8",focus:"Android interview deep dive · Mocks begin",apply:true,tasks:[
    {g:"android",t:"amitshekhariitbhu/android-interview-questions repo"},
    {g:"android",t:"Write own answers to top 20 Android Qs"},
    {g:"android",t:"Pramp.com: 1 coding mock + 1 system design mock"},
    {g:"dsa",t:"NeetCode Graphs: Number of Islands (30 min)"},
    {g:"dsa",t:"NeetCode Graphs: Clone Graph"},
    {g:"dsa",t:"NeetCode Graphs: Pacific Atlantic Water Flow"},
    {g:"git",t:"Project: android-interview-qa — top 20 Q&A by topic"},
    {g:"apply",t:"Full send — 5–10/week"},
  ]},
  {w:15,p:5,dates:"Sep 9–15",focus:"Mock interviews + resume final polish",apply:true,tasks:[
    {g:"android",t:"Get Hired Guide — complete in full"},
    {g:"android",t:"Pramp.com: 2 more mocks (coding + behavioural)"},
    {g:"android",t:"Customise resume summary per role"},
    {g:"dsa",t:"NeetCode Review & retry all failures · explain out loud (30 min)"},
    {g:"git",t:"Project: mock-interview-notes — iterations + gap analysis"},
    {g:"apply",t:"Full send — 5–10/week · LinkedIn informational calls"},
  ]},
  {w:16,p:5,dates:"Sep 16–22",focus:"Active applications · keep engines running",apply:true,tasks:[
    {g:"android",t:"App Challenges — 1 more if bandwidth allows"},
    {g:"android",t:"Targets: Vanguard, Independence Blue Cross, Comcast, fintechs"},
    {g:"android",t:"Negotiate offers confidently — levels.fyi for comp data"},
    {g:"dsa",t:"NeetCode — keep going 30 min/day, fix weak spots same day"},
    {g:"git",t:"Project: oss-contribution-or-polish — OSS PR or final polish"},
    {g:"apply",t:"Full send — 5–10/week"},
  ]},
];

const GROUP_LABELS = {android:"Android Study",dsa:"DSA · LeetCode (daily)",git:"GitHub Project",apply:"Job Applications"};

const RESOURCES = [
  {cat:"Kotlin",items:[
    {n:"Philipp Lackner – Kotlin Crash Course",w:"Week 1",u:"https://www.youtube.com/results?search_query=philipp+lackner+kotlin+crash+course"},
    {n:"Kotlin Koans (interactive)",w:"Week 1",u:"https://play.kotlinlang.org/koans"},
    {n:"Kotlin Collections docs",w:"Week 1",u:"https://kotlinlang.org/docs/collections-overview.html"},
    {n:"Roman Elizarov – Coroutines ⭐",w:"Week 2",u:"https://www.youtube.com/results?search_query=roman+elizarov+kotlin+coroutines"},
  ]},
  {cat:"Android Core & Compose",items:[
    {n:"Android App Architecture guide ⭐",w:"Weeks 3, 7",u:"https://developer.android.com/topic/architecture"},
    {n:"PL Coding – Compose Masterclass",w:"Weeks 4–6",u:"https://pl-coding.com/courses/compose-masterclass",paid:true},
    {n:"Stevdza-San – Compose playlist ⭐",w:"Weeks 4–6",u:"https://www.youtube.com/@stevdza-san"},
    {n:"Compose docs + codelabs",w:"Weeks 4–6",u:"https://developer.android.com/jetpack/compose"},
    {n:"google/nowinandroid ⭐",w:"Weeks 7–8",u:"https://github.com/android/nowinandroid"},
  ]},
  {cat:"Testing & CI/CD",items:[
    {n:"PL Coding – Workshop Collection (Testing)",w:"Week 8",u:"https://pl-coding.com",paid:true},
    {n:"Philipp Lackner – Testing playlist ⭐",w:"Week 8",u:"https://www.youtube.com/results?search_query=philipp+lackner+android+testing"},
    {n:"Android Testing codelabs",w:"Week 8",u:"https://developer.android.com/codelabs"},
  ]},
  {cat:"AI · ML Kit · Gemini",items:[
    {n:"Google ML Kit codelabs ⭐",w:"Week 10",u:"https://developers.google.com/ml-kit/guides"},
    {n:"Gemini API for Android ⭐",w:"Weeks 10–11",u:"https://ai.google.dev/gemini-api/docs/quickstart?lang=android"},
  ]},
  {cat:"DSA · LeetCode",items:[
    {n:"NeetCode 150 roadmap ⭐",w:"Weeks 1–16",u:"https://neetcode.io/practice"},
    {n:"NeetCode YouTube ⭐",w:"Weeks 1–16",u:"https://www.youtube.com/@NeetCode"},
    {n:"LeetCode (Kotlin)",w:"Weeks 1–16",u:"https://leetcode.com"},
  ]},
  {cat:"System Design",items:[
    {n:"ByteByteGo ⭐",w:"Weeks 13–16",u:"https://www.youtube.com/@ByteByteGo"},
    {n:"weeeBox/mobile-system-design ⭐",w:"Weeks 13–14",u:"https://github.com/weeeBox/mobile-system-design"},
    {n:"Udemy – Android System Design Interview",w:"Week 13",u:"https://www.udemy.com/courses/search/?q=master+android+system+design+interview",paid:true},
  ]},
  {cat:"Interview & Job Search",items:[
    {n:"amitshekhariitbhu/android-interview-questions ⭐",w:"Weeks 14–15",u:"https://github.com/amitshekhariitbhu/android-interview-questions"},
    {n:"Pramp – free mock interviews ⭐",w:"Weeks 14–15",u:"https://www.pramp.com"},
    {n:"LinkedIn Jobs",w:"Week 4+",u:"https://www.linkedin.com/jobs"},
    {n:"levels.fyi – salary data",w:"Offer stage",u:"https://www.levels.fyi"},
  ]},
];

const PLAN_START = new Date(2026,5,3); // Jun 3 2026 = Week 1
